services:
  app:
    build:
      context: .
      args:
        - USERNAME=${USERNAME}
        - GROUPNAME=${GROUPNAME}
        - UID=${UID}
        - GID=${GID}
    command: /bin/bash
    ports:
      - "3000:3000"
    volumes:
      - ./:/workspace
    tty: true
    user: "${UID}:${GID}"
    working_dir: /workspace
